export const MEDICAL_SPECIALIZATIONS = [
  { id: 'cardiologist', en: 'Cardiologist', ar: 'أخصائي قلب' },
  { id: 'dermatologist', en: 'Dermatologist', ar: 'أخصائي جلدية' },
  { id: 'pediatrician', en: 'Pediatrician', ar: 'أخصائي أطفال' },
  { id: 'ophthalmologist', en: 'Ophthalmologist', ar: 'أخصائي عيون' },
  { id: 'orthopedic', en: 'Orthopedic Surgeon', ar: 'جراح عظام' },
  { id: 'neurologist', en: 'Neurologist', ar: 'أخصائي أعصاب' },
  { id: 'psychiatrist', en: 'Psychiatrist', ar: 'أخصائي طب نفسي' },
  { id: 'gynecologist', en: 'Gynecologist/Obstetrician', ar: 'أخصائي نساء وتوليد' },
  { id: 'dentist', en: 'Dentist', ar: 'طبيب أسنان' },
  { id: 'internal_medicine', en: 'Internal Medicine', ar: 'طب باطني' },
  { id: 'general_practitioner', en: 'General Practitioner', ar: 'طبيب عام' },
  { id: 'radiologist', en: 'Radiologist', ar: 'أخصائي أشعة' },
  { id: 'pathologist', en: 'Pathologist', ar: 'أخصائي تحليل' },
  { id: 'surgeon', en: 'Surgeon', ar: 'جراح عام' },
  { id: 'ent', en: 'ENT Specialist', ar: 'أخصائي أنف وأذن وحنجرة' },
  { id: 'urologist', en: 'Urologist', ar: 'أخصائي مسالك بولية' },
  { id: 'endocrinologist', en: 'Endocrinologist', ar: 'أخصائي غدد صماء' },
  { id: 'oncologist', en: 'Oncologist', ar: 'أخصائي أورام' },
];
